name: 'cargo-publish-action'
description: 'Publish packages to crates.io, when a new version  has been detected'
author: 'Martijn Gribnau'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
